# Generated by Django 6.0.1 on 2026-02-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_category_event_college_mode_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
