# Generated by Django 6.0.1 on 2026-02-28 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_memorybook_uploaded_by_alter_event_status_and_more'),
        ('users', '0002_college_user_is_college_verified_user_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_events', to='users.college'),
        ),
        migrations.AddField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('COLLEGE', 'College Only')], default='PUBLIC', max_length=15),
        ),
    ]
