# Generated by Django 6.0.1 on 2026-02-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_mode', models.BooleanField(default=False)),
                ('allowed_domains', models.CharField(blank=True, default='gmail.com, edu', max_length=255)),
                ('max_events_per_organizer', models.IntegerField(default=5)),
                ('cancellation_policy', models.CharField(choices=[('flexible', 'Flexible (24h before)'), ('moderate', 'Moderate (50% refund)'), ('strict', 'Strict (No refund)')], default='flexible', max_length=20)),
                ('password_policy', models.CharField(choices=[('weak', 'Weak'), ('medium', 'Medium'), ('strong', 'Strong')], default='strong', max_length=20)),
                ('session_timeout', models.IntegerField(default=30)),
                ('enable_chatbot', models.BooleanField(default=True)),
                ('enable_memory_book', models.BooleanField(default=True)),
                ('enable_feedback_moderation', models.BooleanField(default=False)),
            ],
        ),
    ]
